### ISSUE TITLE
Not an issue: a query

### ISSUE THREAD

**Issue by vandana-rajan** [AmirSh15/graph_emotion_recognition#1]
Hi Amir,

Thanks for sharing the code. Nice work :) 

I have a query regarding the experiments. If I am not wrong, RML, eNTERFACE, RAVDESS and IEMOCAP are all video datasets. But you have used the first 3 datasets for face emotion recognition and the last one for SER. Is there any particular reason for this? 

Thanks,
VR

**Comment by AmirSh15** [comment]
Hi Vandana,

Thanks. There is no particular reason behind selecting the databases. I just followed the literature. Most dynamic FER used RML, eNTERFACE, and RAVDESS. Similarly, the SER literature mostly experiments on IEMOCAP. But I've seen some papers which used IEMOCAP for the multi-modal emotion recognition approach.


Best regards,
Amir

—
Amir Shirian
PhD student in Computer Science, University of Warwick, Coventry, CV4 7AL, UK


________________________________
From: Vandana Rajan ***@***.***>
Sent: Wednesday, June 16, 2021 11:22 AM
To: AmirSh15/graph_emotion_recognition ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AmirSh15/graph_emotion_recognition] Not an issue: a query (#1)


Hi Amir,

Thanks for sharing the code. Nice work :)

I have a query regarding the experiments. If I am not wrong, RML, eNTERFACE, RAVDESS and IEMOCAP are all video datasets. But you have used the first 3 datasets for face emotion recognition and the last one for SER. Is there any particular reason for this?

Thanks,
VR

**Comment by vandana-rajan** [comment]
I see. Thanks for the prompt reply.
