### ISSUE TITLE
some questions about paper

### ISSUE THREAD

**Issue by lulu8040043** [AmirSh15/graph_emotion_recognition#2]
Dear Amir, I'm Lulu , a graduate student from China. Your paper inspired me a lot, but I don't quite understand some problems in the graph construction.
 I would like to ask ① in thesis III. PROPOSED APPROACH B. Learnable graph inception network• Learnable pooling for graph-level representation. Why use a layer of sumpooling and a layer of meanpooling?
② In • Learnable adjacency (A). What does A cross Ad stand for?
I would appreciate it if you could answer my questions.
By the way, I may have further questions to ask you. Can I get your email address?

**Comment by AmirSh15** [comment]
Hi Lulu,

Sorry for the late response. Could you please send your questions to my email (amirdonte15@gmail.com)?
